import {songAt,songFrets,songAction,renderScore,scoreBar} from './song.js';
import {practiceSessionKey,readPracticeSession} from './practice-session.js';
import {t, html, installLanguageControl, setPageLanguage, languageURL} from './i18n.js';
import './style.css';
import {Ukulele} from './model.js';
import {AudioEngine} from './audio.js';
import {strokeDuration} from './hand-motion.js';
import {chords,lessons,patterns,lyrics,melody,scaleNotes,tuning,stringNames} from './data.js';
setPageLanguage();
const $=s=>document.querySelector(s);
const icons={play:'<path d="m8 5 11 7-11 7z"/>',pause:'<path d="M8 5v14M16 5v14"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',book:'<path d="M12 5v15m0-15C8 2 4 3 2 4v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-2-1-6-2-10 1Z"/>',music:'<path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="3"/><ellipse cx="17" cy="16" rx="3" ry="3"/>',tune:'<path d="M5 3v18M12 3v18M19 3v18M2 8h6M9 16h6M16 6h6"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3M3 12h4v8H3zM17 12h4v8h-4z"/>',reset:'<path d="M3 10a9 9 0 1 1 2 9M3 4v6h6"/>',step:'<path d="m5 5 10 7-10 7zM19 5v14"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',light:'<path d="M9 18h6m-6 3h6M8 14a6 6 0 1 1 8 0l-1 3H9z"/>',rotate:'<path d="M3 10a9 9 0 0 1 16-5l2 3m0-6v6h-6M21 14a9 9 0 0 1-16 5l-2-3m0 6v-6h6"/>',volume:'<path d="m11 4-6 5H2v6h3l6 5zM15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.music}</svg>`;
let saved={};try{const parsed=JSON.parse(localStorage.getItem('manmantan-v1')||'{}');saved=parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{};}catch{}
let lessonIndex=Number.isInteger(saved.lesson)&&saved.lesson>=0&&saved.lesson<lessons.length?saved.lesson:0;
if(new URLSearchParams(location.search).get('song')==='twinkle')lessonIndex=lessons.findIndex(l=>l.id==='twinkle');
let completed=new Set(Array.isArray(saved.completed)?saved.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<lessons.length):[]);
const state={playing:false,step:0,bpm:60,pattern:'down',loop:true,metronome:true,melody:false,mode:'follow',selectedChord:'C',countIn:0,nextTime:0,lastStep:0,view:'front'};
const audio=new AudioEngine();let model;
function save(){try{localStorage.setItem('manmantan-v1',JSON.stringify({lesson:lessonIndex,completed:[...completed]}));}catch{}}
const navGroups=[[t('开始弹奏'),0,4],[t('听懂节奏'),4,8],[t('弹唱进阶'),8,11],[t("曲谱练习"),11,lessons.length]];
$('#app').innerHTML=html(`<aside class="sidebar"><a class="brand" href="#" aria-label="慢慢弹首页"><span class="brand-icon">♪</span><span>慢慢弹<small>PLAY A LITTLE, EVERY DAY</small></span></a><div class="sidebar-intro">你的第一间尤克里里练习室</div><div class="nav-heading">学习路线 <span>${t('{count} 节练习',{count:lessons.length})}</span></div><nav id="lesson-nav"></nav><div class="progress-box"><span>一点一点，也在向前</span><b id="progress-label"></b><div class="progress-track"><div id="progress-fill"></div></div><small>学习进度保存在这台设备</small></div><a class="source-side" href="https://www.bilibili.com/video/BV1st411q7yc" target="_blank" rel="noopener">${icon('book')} 参考课程 · 莉莉克丝 ${icon('external')}</a></aside>
<div class="workspace"><header class="topbar"><div class="breadcrumb">我的练习室 <span>/</span> <strong id="breadcrumb"></strong></div><button class="outline small" id="tune">${icon('tune')} 听音调弦</button></header>
<main><div class="lesson-heading"><div><div class="eyebrow"><span class="dot"></span> 跟着看，慢慢弹 <span id="lesson-number"></span></div><h1 id="lesson-title"></h1><p id="lesson-subtitle"></p></div><a id="source-link" class="source-link" target="_blank" rel="noopener">${icon('play')} 对照原课 ${icon('external')}</a></div>
<div class="practice-grid"><section class="visual-panel"><div class="panel-toolbar"><div class="live-label"><span class="dot"></span> 3D 指法演示</div><div class="segmented" id="views"><button data-view="front" class="active">正面</button><button data-view="fret">指板特写</button><button data-view="angle">侧面</button></div><button id="reset-view" class="icon-button" aria-label="重置视角">${icon('reset')}</button></div>
<div class="model-stage"><div class="stage-watermark">FEEL THE STRINGS.</div><div id="three-host"></div><div class="current-float"><span id="current-label">当前和弦</span><strong id="current-chord">C</strong><small id="next-chord">接下来 Am</small></div><div class="motion-float"><span>右手动作</span><strong id="strum-symbol">↓</strong><small id="strum-text">向下轻扫</small></div><div class="model-help">${icon('rotate')} 拖动旋转 · 滚轮缩放 <span>标准高 G · 右手持琴</span></div></div>
<div class="finger-key"><span>左手手指</span><span><i class="finger f1">1</i> 食指</span><span><i class="finger f2">2</i> 中指</span><span><i class="finger f3">3</i> 无名指</span><span><i class="finger f4">4</i> 小指</span><small>数字圆点 = 按弦位置</small></div>
<div id="song-follow" class="song-follow" hidden></div><div class="transport"><div class="transport-main"><button id="restart" class="icon-button" aria-label="从头开始">${icon('reset')}</button><button id="play" class="primary">${icon('play')} 开始跟练</button><button id="step" class="icon-button" aria-label="下一半拍">${icon('step')}</button><span id="transport-status" role="status">准备好了，从第一拍开始</span></div><div class="tempo"><label for="tempo">速度 <b id="bpm-value">60</b> <small>BPM</small></label><input id="tempo" type="range" min="40" max="120" step="2" value="60" aria-label="练习速度"><button id="slow" class="speed-preset">慢速</button></div></div>
<div class="transport-options"><label><input type="checkbox" id="loop" checked> 循环练习</label><label><input type="checkbox" id="metronome" checked> 节拍器</label><label><input type="checkbox" id="sound" checked> 琴声</label><span>空格 播放 / 暂停 <kbd>→</kbd> 单步</span></div></section>
<aside class="guide-panel"><div class="guide-heading"><span>${icon('book')} 左手，按这里</span><span id="chord-name">C 大三和弦</span></div><div id="chord-diagram"></div><p class="chord-hint" id="chord-hint"></p><div id="chord-buttons" class="chord-buttons"></div><div class="mode-row"><button class="text-button" id="follow-mode">${icon('rotate')} 已跟随课程自动换和弦</button></div><div class="guide-divider"></div><div class="mini-label">为什么这样按？</div><p id="chord-why" class="why"></p><div class="tip-box">${icon('light')}<div><strong>小提醒</strong><p id="lesson-tip"></p></div></div></aside></div>
<section class="rhythm-panel"><div class="section-heading"><div><span class="eyebrow">RHYTHM & VOICE</span><h2 id="rhythm-title">把每一拍，看清楚。</h2></div><div class="rhythm-controls"><label class="melody-toggle"><input type="checkbox" id="melody"> 旋律提示音</label><select id="pattern" aria-label="节奏型"><option value="down">基础下扫 · ↓ ↓ ↓ ↓</option><option value="island">常用扫弦 · ↓ ↓↑ ↑↓↑</option><option value="slow">慢速扫弦 · ↓ ↑ ↓ ↑</option><option value="pluck">逐弦拨奏 · 4 3 2 1</option><option value="arp">分解和弦 · 4 — 3 2 1</option><option value="mute">扫弦与切音 · ↓ × ↓↑×↑</option></select></div></div><div class="timeline-label"><span id="timeline-context">四和弦循环</span><span id="timeline-help">4/4 拍 · 每格半拍 · 点击定位</span></div><div id="timeline" class="timeline"></div><div class="rhythm-legend"><span><b>↓</b> 向下扫</span><span><b>↑</b> 向上扫</span><span><b>—</b> 留空，保持摆动</span><span><b>×</b> 轻触制音</span><span>歌词为本站原创短练习 · 可打开旋律跟唱</span></div></section>
<section class="learn-panel"><div class="learn-intro"><span class="eyebrow">ONE SMALL STEP</span><h2>这一节，练会什么？</h2><p id="lesson-goal"></p><button id="complete" class="outline">${icon('check')} 我练会了，下一节 ${icon('arrow')}</button></div><div id="lesson-steps" class="lesson-steps"></div></section>
<footer>每天给音乐一点时间。<span>参考课程目录：莉莉克丝 · 本站为独立可视化练习，非原课程逐帧转制</span></footer></main></div>
<dialog id="tune-dialog"><div class="dialog-top"><span class="eyebrow">BEFORE YOU PLAY</span><button class="icon-button" id="close-tune" aria-label="关闭调弦窗口">${icon('close')}</button></div><h2>先让四根弦，找到自己的声音。</h2><p>标准高 G 调弦。点一根弦听参考音，再轻拨你的琴弦作对照。</p><div class="tuning-strings">${['G4','C4','E4','A4'].map((n,i)=>`<button data-tuning="${i}"><small>${t('第 {string} 弦',{string:4-i})}</small><b>${n}</b><span>${[392,261.63,329.63,440][i]} Hz</span>${icon('volume')}</button>`).join('')}</div><div class="tuning-note">琴颈朝左、琴面朝外时，从靠近脸的一根弦向下依次是 G、C、E、A。这是参考音工具，不会使用麦克风或自动检测音准。</div><button id="stop-tuning" class="outline">停止参考音</button></dialog><div class="toast" role="status" id="toast"></div>`);
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function renderNav(){let html='';for(const [name,start,end] of navGroups)html+=`<div class="nav-group">${name}</div>`+lessons.slice(start,end).map((l,i)=>{const n=start+i;return `<button class="lesson-link ${n===lessonIndex?'active':''}" data-lesson="${n}" ${n===lessonIndex?'aria-current="step"':''}><span class="nav-number ${completed.has(n)?'done':''}">${completed.has(n)?'✓':String(n+1).padStart(2,'0')}</span><span>${l.tag}</span>${n===lessonIndex?'<span class="nav-playing">▥</span>':''}</button>`;}).join('');$('#lesson-nav').innerHTML=html;$('#progress-label').textContent=`${completed.size} / ${lessons.length}`;$('#progress-fill').style.width=`${completed.size/lessons.length*100}%`;}
function diagram(frets,fingers){let svg=html('<svg viewBox="0 0 240 185" role="img" aria-label="和弦指法图，从左到右为第4、3、2、1弦"><g font-family="sans-serif" text-anchor="middle">');for(let s=0;s<4;s++){let x=70+s*34;svg+=`<text x="${x}" y="18" fill="#7d817a" font-size="12">${stringNames[s]}</text><text x="${x}" y="39" fill="#738577" font-size="14">${frets[s]?'':'○'}</text><path d="M${x} 48V160" stroke="#958b7b" stroke-width="1.3"/>`;}
 for(let n=0;n<5;n++){svg+=`<path d="M69 ${48+n*28}H173" stroke="${n?'#c9c1b5':'#706657'}" stroke-width="${n?1:5}"/>`;if(n<4)svg+=`<text x="49" y="${66+n*28}" font-size="10" fill="#9e988e">${n+1}</text>`;}
 const colors=['','#de8054','#779575','#6c92ad','#a487ae'];frets.forEach((f,s)=>{if(f)svg+=`<circle cx="${70+s*34}" cy="${48+(f-.5)*28}" r="11" fill="${colors[fingers[s]]}"/><text x="${70+s*34}" y="${52+(f-.5)*28}" font-size="12" font-weight="600" fill="white">${fingers[s]}</text>`;});svg+=html('<text x="121" y="181" fill="#929487" font-size="10">○ 空弦 · 数字为手指编号</text></g></svg>');return svg;}
function current(){const lesson=lessons[lessonIndex];const bar=Math.floor(state.step/8)%lesson.sequence.length;return {lesson,bar,chord:state.mode==='single'?state.selectedChord:lesson.sequence[bar],slot:state.step%8};}
function displayChord(){const {lesson,bar,chord,slot}=current();let data=chords[chord];let frets=[...data.frets],fingers=data.fingers;let title=chord,name=data.name,hint=data.hint,why=data.why;if(lesson.type==='open'){frets=[0,0,0,0];fingers=[0,0,0,0];title='○';name=t('四根空弦');hint=t('左手暂时不按弦，只看右手标亮的弦。');why=t('空弦就是不用左手按住任何品位，直接拨响琴弦。');}else if(lesson.type==='scale'){const note=scaleNotes[slot];frets=[0,0,0,0];frets[note.s]=note.f;fingers=frets.map(f=>f);title=['C','D','E','F','G','A','B','C'][slot];name=['do','re','mi','fa','sol','la','si','do'][slot]+t(' · 单音练习');hint=t('拨第 {string} 弦，{position}。每半拍弹一个音。',{string:4-note.s,position:note.f?t('按 {fret} 品',{fret:note.f}):t('保持空弦')});why=t('C 大调由 C、D、E、F、G、A、B 七个音组成，最后回到高八度的 C。');}
 if(lesson.type==='song'){
 const note=songAt(state.step);frets=songFrets(note);fingers=frets.map(f=>f);title=note.pitch;name=note.solfege+' · '+t('旋律单音');
 hint=t('拨第 {string} 弦，{position}。',{string:4-note.s,position:note.f?t('按 {fret} 品',{fret:note.f}):t('保持空弦')})+' '+(note.beats===1?t('保持一拍。'):t('保持两拍。'));why=t('简谱数字表示旋律，四线谱数字表示品位。只拨标出的那根弦。');
 }
 $('#current-label').textContent=lesson.type==='song'?t('当前音符'):t('当前和弦');
 $('#current-chord').textContent=title;$('#next-chord').textContent=lesson.type==='song'?(songAt(songAt(state.step).end)?t('下一个音 {note}',{note:songAt(songAt(state.step).end).pitch}):t('最后一个音')):lesson.type==='scale'?t('一个音半拍'):lesson.type==='open'?'G · C · E · A':state.mode==='single'?t('单和弦循环'):t('接下来 {chord}',{chord:lesson.sequence[(bar+1)%lesson.sequence.length]});$('#chord-name').textContent=name;$('#chord-diagram').innerHTML=diagram(frets,fingers);$('#chord-hint').textContent=hint;$('#chord-why').textContent=why;$('#chord-buttons').innerHTML=['open','scale','song'].includes(lesson.type)?'':Object.keys(chords).map(key=>`<button data-chord="${key}" class="${key===chord?'active':''}" aria-pressed="${key===chord}">${key}</button>`).join('');model?.setFingers(frets,fingers);$('#follow-mode').hidden=lesson.type==='song';$('#follow-mode').disabled=['open','scale','song'].includes(lesson.type);$('#follow-mode').innerHTML=icon('rotate')+(state.mode==='single'?t('单和弦模式 · 点此恢复跟随'):t('已跟随课程自动换和弦'));}
function action(){const {lesson,slot}=current();return lesson.type==='song'?songAction(state.step):lesson.type==='scale'?'P'+(4-scaleNotes[slot].s):patterns[state.pattern][slot];}
function actionLabel(a){return a==='H'?['⌒',t('保持余音，不再拨弦')]:a==='D'?['↓',t('向下轻扫')]:a==='U'?['↑',t('向上轻扫')]:a==='X'?['×',t('轻触制音')]:a==='-'?['—',t('留空，手腕继续摆动')]:[a.slice(1),t('轻拨第 {string} 弦',{string:a.slice(1)})];}
function renderTimeline(){const {lesson}=current();const isSong=lesson.type==='song';const isScale=lesson.type==='scale';
 $('#rhythm-title').textContent=isSong?t('跟着曲谱，弹小星星。'):t('把每一拍，看清楚。');
 $('.rhythm-controls').hidden=isSong;$('.rhythm-legend').hidden=isSong;
 $('#timeline').classList.toggle('song-score',isSong);$('#song-follow').hidden=!isSong;
 $('#timeline-help').textContent=isSong?t('每格一拍 · 点击试听并定位'):t('4/4 拍 · 每格半拍 · 点击定位');
 if(isSong){$('#timeline-context').textContent=t('简谱 + 四线谱 · 0 是空弦，横线是延音');$('#timeline').innerHTML=renderScore();updateActive();return;}
$('#timeline-context').textContent=isScale?t('C 大调上行音阶'):lesson.type==='open'?t('认识四根空弦'):state.mode==='single'?t('{chord} · 单和弦练习',{chord:state.selectedChord}):t('四和弦循环 · 原创弹唱练习');$('#pattern').disabled=isScale||lesson.type==='open';$('#timeline').innerHTML=lesson.sequence.map((ch,b)=>`<div class="bar"><div class="bar-title"><b style="color:${chords[ch].color}">${isScale?t('C 大调'):lesson.type==='open'?t('空弦'):state.mode==='single'?state.selectedChord:ch}</b><span>${t('{bar} 小节',{bar:String(b+1).padStart(2,'0')})}</span></div><div class="beat-cells">${Array.from({length:8},(_,i)=>{let a=isScale?'P'+(4-scaleNotes[i].s):patterns[state.pattern][i];return `<button class="beat-cell" data-step="${b*8+i}" aria-label="${t(i%2?'第{bar}小节第{beat}拍后半拍':'第{bar}小节第{beat}拍',{bar:b+1,beat:Math.floor(i/2)+1})}"><small>${i%2?'&':i/2+1}</small><b class="${a==='-'?'rest':''}">${actionLabel(a)[0]}</b><span>${isScale?['do','re','mi','fa','sol','la','si','do'][i]:lesson.type==='open'?stringNames[4-Number(a[1])]:lyrics[b%4][i]}</span></button>`;}).join('')}</div></div>`).join('');updateActive();}
function updateActive(){
 if(current().lesson.type==='song'){
 const bar=Math.floor(state.step/8);
 if($('#song-follow').dataset.bar!==String(bar)){$('#song-follow').innerHTML=scoreBar(bar);$('#song-follow').dataset.bar=bar;}
 document.querySelectorAll('.score-beat').forEach(e=>{const active=Number(e.dataset.step)===state.step-state.step%2;e.classList.toggle('active',active);if(active)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});
 }
document.querySelectorAll('.beat-cell').forEach(e=>e.classList.toggle('active',Number(e.dataset.step)===state.step));const [symbol,text]=actionLabel(action());$('#strum-symbol').textContent=symbol;$('#strum-text').textContent=text;}
function renderPlay(){$('#play').innerHTML=icon(state.playing?'pause':'play')+(state.playing?t('暂停练习'):t('开始跟练'));$('#play').setAttribute('aria-label',state.playing?t('暂停练习'):t('开始跟练'));}
function stop(keepPose=false){state.playing=false;state.countIn=0;audio.stop();model?.pause(keepPose);displayChord();renderPlay();}
async function play(){if(state.playing){stop(true);$('#transport-status').textContent=t('已暂停，可以慢慢看清指法');return;}try{await audio.init();if(current().lesson.type==='song'){state.step=songAt(state.step).start;displayChord();updateActive();}state.playing=true;state.countIn=4;state.nextTime=audio.time;state.lastStep=state.step-1;renderPlay();}catch{notify(t('浏览器未能启用声音，请再次点击播放。'));}}
function perform(){displayChord();updateActive();const {lesson,chord,slot,bar}=current();let a=action();if($('#sound').checked){if(lesson.type==='song'){const note=songAt(state.step);if(note.attack)audio.note(note.n,0,note.beats*60/state.bpm*.95);}else if(lesson.type==='scale')audio.note(scaleNotes[slot].n);else if(a==='D'||a==='U')audio.chord(chords[chord].frets,a,strokeDuration(30/state.bpm));else if(a.startsWith('P')){let s=4-Number(a[1]);audio.note(tuning[s]+(lesson.type==='open'?0:chords[chord].frets[s]));}else if(a==='X')audio.mute();}if(a==='H')model?.showAction('H');else model?.pulse(a,30/state.bpm);if(state.playing)prepareNextFingers();if(state.metronome&&slot%2===0)audio.click(slot===0);if(state.melody&&!['scale','open','song'].includes(lesson.type))audio.note(melody[bar%4][slot],0,60/state.bpm*.43,true);$('#transport-status').textContent=t(slot%2?'第 {bar} 小节 · 第 {beat} 拍 后半拍':'第 {bar} 小节 · 第 {beat} 拍',{bar:bar+1,beat:Math.floor(slot/2)+1});}
function prepareNextFingers(){
 const {lesson,slot,bar}=current();
 if(lesson.type==='song'){
  return; // Keep fretted notes held for their full duration.
 }else if(lesson.type==='scale'){
  const note=scaleNotes[(slot+1)%8],frets=[0,0,0,0];frets[note.s]=note.f;
  if(state.loop||state.step+1<lesson.sequence.length*8)model?.prepareFingers(frets,30/state.bpm);
 }else if(lesson.type!=='open'&&slot===7&&state.mode==='follow'&&(state.loop||bar+1<lesson.sequence.length)){
  model?.prepareFingers(chords[lesson.sequence[(bar+1)%lesson.sequence.length]].frets,30/state.bpm);
 }
}
async function step(){stop();await audio.init();state.step=(current().lesson.type==='song'?state.step-state.step%2+2:state.step+1)%(lessons[lessonIndex].sequence.length*8);perform();}
function tick(){requestAnimationFrame(tick);if(!state.playing||audio.time<state.nextTime)return;const beat=60/state.bpm;if(state.countIn>0){$('#transport-status').textContent=t('预备 {count} / 4 · 跟着数拍',{count:5-state.countIn});if(state.metronome)audio.click(state.countIn===4);state.countIn--;state.nextTime=audio.time+beat;return;}if(state.lastStep===state.step){state.step++;if(state.step>=lessons[lessonIndex].sequence.length*8){if(state.loop)state.step=0;else{state.step--;stop();$('#transport-status').textContent=t('本轮练习完成，做得不错。');return;}}}perform();state.lastStep=state.step;state.nextTime=audio.time+beat/2;}
function loadLesson(n){stop();lessonIndex=n;const lesson=lessons[n];Object.assign(state,{step:0,bpm:lesson.bpm,pattern:lesson.pattern,mode:'follow',selectedChord:'C',melody:lesson.type==='sing'});$('#melody').checked=state.melody;$('#melody').disabled=['scale','open','song'].includes(lesson.type);$('#tempo').value=state.bpm;$('#bpm-value').textContent=state.bpm;$('#pattern').value=state.pattern;$('#breadcrumb').textContent=lesson.tag;$('#lesson-number').textContent=`LESSON ${String(n+1).padStart(2,'0')}`;$('#lesson-title').textContent=lesson.title;$('#lesson-subtitle').textContent=lesson.subtitle;$('#source-link').href=lesson.sourceURL||`https://www.bilibili.com/video/BV1st411q7yc/?p=${n+1}`;$('#source-link').innerHTML=icon('external')+(lesson.type==='song'?t('曲谱参考'):t('对照原课'));$('#step').setAttribute('aria-label',lesson.type==='song'?t('下一拍'):t('下一半拍'));const url=new URL(location.href);if(lesson.id)url.searchParams.set('song',lesson.id);else url.searchParams.delete('song');history.replaceState(null,'',url);$('#source-link').title=lesson.source;$('#lesson-goal').textContent=lesson.goal;$('#lesson-tip').textContent=lesson.tip;$('#lesson-steps').innerHTML=lesson.steps.map((s,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${s}</p></div>`).join('');$('#transport-status').textContent=t('准备好了，从第一拍开始');$('#complete').innerHTML=icon('check')+(n===lessons.length-1?t('标记本节已完成'):t('我练会了，下一节 ')+icon('arrow'));renderNav();displayChord();renderTimeline();save();}
$('#lesson-nav').addEventListener('click',e=>{const b=e.target.closest('[data-lesson]');if(b)loadLesson(Number(b.dataset.lesson));});
$('#play').onclick=play;$('#step').onclick=step;$('#restart').onclick=()=>{stop();state.step=0;displayChord();updateActive();$('#transport-status').textContent=t('已回到第一拍');};
$('#tempo').oninput=e=>{state.bpm=Number(e.target.value);$('#bpm-value').textContent=state.bpm;};$('#slow').onclick=()=>{$('#tempo').value=40;state.bpm=40;$('#bpm-value').textContent=40;notify(t('已放慢到 40 BPM，慢慢来。'));};
$('#loop').onchange=e=>state.loop=e.target.checked;$('#metronome').onchange=e=>state.metronome=e.target.checked;$('#melody').onchange=e=>state.melody=e.target.checked;$('#sound').onchange=()=>audio.stop();
$('#pattern').onchange=e=>{stop();state.pattern=e.target.value;state.step=0;displayChord();renderTimeline();};
$('#chord-buttons').onclick=async e=>{const b=e.target.closest('[data-chord]');if(!b)return;stop();state.mode='single';state.selectedChord=b.dataset.chord;state.step=0;displayChord();renderTimeline();await audio.init();if($('#sound').checked)audio.chord(chords[state.selectedChord].frets,'D',strokeDuration(.5));model?.pulse('D');};
$('#follow-mode').onclick=()=>{stop();state.mode='follow';state.step=0;displayChord();renderTimeline();};
$('#song-follow').onclick=$('#timeline').onclick=async e=>{const b=e.target.closest('[data-step]');if(!b)return;stop();state.step=Number(b.dataset.noteStart??b.dataset.step);await audio.init();perform();};
$('#views').onclick=e=>{const b=e.target.closest('[data-view]');if(b){model?.view(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));}};$('#reset-view').onclick=()=>{model?.view('front');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='front'));};
$('#complete').onclick=()=>{completed.add(lessonIndex);save();notify(t('这一小步已记下，继续慢慢弹。'));if(lessonIndex<lessons.length-1)loadLesson(lessonIndex+1);else renderNav();};
$('#tune').onclick=()=>{stop();$('#tune-dialog').showModal();};$('#close-tune').onclick=()=>$('#tune-dialog').close();$('#tune-dialog').addEventListener('close',()=>audio.stop());$('#tune-dialog').onclick=async e=>{const b=e.target.closest('[data-tuning]');if(b){await audio.init();audio.stop();const s=Number(b.dataset.tuning);audio.note(tuning[s],0,2);document.querySelectorAll('[data-tuning]').forEach(x=>x.classList.toggle('active',x===b));}};$('#stop-tuning').onclick=()=>audio.stop();
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||(e.target.tagName==='BUTTON'&&e.target.id!=='play')||$('#tune-dialog').open)return;if(e.code==='Space'){e.preventDefault();play();}if(e.code==='ArrowRight'){e.preventDefault();step();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.playing){stop(true);$('#transport-status').textContent=t('页面已离开，练习自动暂停');}});
try{model=new Ukulele($('#three-host'));}catch(e){$('#three-host').innerHTML=html('<div class="webgl-fallback">当前浏览器无法开启 3D。<br>仍可使用右侧指法图和下方节拍练习。</div>');}
loadLesson(lessonIndex);
try {
 const raw=sessionStorage.getItem(practiceSessionKey);sessionStorage.removeItem(practiceSessionKey);
 const restored=readPracticeSession(JSON.parse(raw||'null'),lessonIndex,lessons[lessonIndex].sequence.length*8);
 if(restored){
  Object.assign(state,restored,{playing:false});
  state.step%=lessons[lessonIndex].sequence.length*8;
  if(['open','scale','song'].includes(lessons[lessonIndex].type)){state.mode='follow';state.pattern=lessons[lessonIndex].pattern;state.melody=false;}
  $('#tempo').value=state.bpm;$('#bpm-value').textContent=state.bpm;$('#pattern').value=state.pattern;
  for(const id of ['loop','metronome','melody'])$('#'+id).checked=state[id];
  if(typeof restored.sound==='boolean')$('#sound').checked=restored.sound;
  const contacts=$('.show-contacts');if(contacts&&restored.contacts){contacts.checked=true;model.fingerGroup.visible=true;}
  displayChord();renderTimeline();renderPlay();$('#transport-status').textContent=t('语言已切换，可以继续练习');
  if(restored.view){model?.view(restored.view);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===restored.view));}
 }
}catch{}
installLanguageControl($('.topbar'),()=>{
 stop(true);save();
 try{sessionStorage.setItem(practiceSessionKey,JSON.stringify({lesson:lessonIndex,step:state.step,bpm:state.bpm,pattern:state.pattern,mode:state.mode,selectedChord:state.selectedChord,loop:state.loop,metronome:state.metronome,melody:state.melody,sound:$('#sound').checked,contacts:$('.show-contacts')?.checked||false,view:$('.segmented .active')?.dataset.view||'front'}));}catch{}
});
tick();
